
desc 'CXLib 针对私有库快速升级维护'
lane :CXLib do |options|

# 打标签需要和podspec的版本对应
tagName = options[:tag]
# 被上传的目标podspec文件
targetName = options[:target]
# 本次更新的内容
msgName = options[:msg]

# git pull
#  git_pull 
# 确认是 master 分支
#  ensure_git_branch

cocoapods(
clean: true,
podfile: "./Example/Podfile"
)

git_add(path: ".")

git_commit(path: ".", message: "#{msgName}")

push_to_git_remote

if git_tag_exists(tag: tagName)
    UI.message("发现tag:#{tagName} 之前有tag,删除原来的标签🚀")
    remove_tag(tag:tagName)
end

add_git_tag(
tag: tagName
)

push_git_tags

pod_lib_lint(allow_warnings: true,use_libraries:true,sources: ['https://github.com/CocoaPods/Specs.git'])

pod_push(path: "#{targetName}.podspec",allow_warnings: true,use_libraries:true)

end
